import React, { useState } from 'react';
import { FileText, Loader2, Download, AlertCircle, CheckCircle2, Pill, Flame } from './Icons';
import { MedicalReport } from '../types';

const API_BASE = (import.meta as any).env?.VITE_API_URL?.replace(/\/+$/, '') || 'http://localhost:5000';

interface Props {
  reports: MedicalReport[];
}

export const DoctorSummary: React.FC<Props> = ({ reports }) => {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generateSummary = async () => {
    if (reports.length === 0) return;
    setLoading(true);
    setError(null);

    try {
      // Build a condensed patient context from all reports
      const sorted = [...reports].sort(
        (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
      );

      const reportSummaries = sorted.map((r, idx) => {
        const parts: string[] = [];
        parts.push(`Report #${idx + 1}: ${r.type || 'Medical Report'} — ${new Date(r.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);

        if (r.analysis?.overview?.overallStatus) {
          parts.push(`  Status: ${r.analysis.overview.overallStatus}`);
        }

        if (r.biomarkers && r.biomarkers.length > 0) {
          const markers = r.biomarkers.map(b => `${b.name}: ${b.value} ${b.unit} (${b.category})`).join('; ');
          parts.push(`  Biomarkers: ${markers}`);
        }

        if (r.analysis?.risks && r.analysis.risks.length > 0) {
          const risks = r.analysis.risks.map(risk => `${risk.condition} [${risk.probability}] — ${risk.reasoning}`).join('; ');
          parts.push(`  Risks: ${risks}`);
        }

        if (r.prescriptions && r.prescriptions.length > 0) {
          const meds = r.prescriptions.map(m => `${m.name} ${m.dosage} (${m.frequency})`).join('; ');
          parts.push(`  Medications: ${meds}`);
        }

        if (r.analysis?.overview?.keyConcerns && r.analysis.overview.keyConcerns.length > 0) {
          parts.push(`  Concerns: ${r.analysis.overview.keyConcerns.join('; ')}`);
        }

        return parts.join('\n');
      }).join('\n\n');

      const prompt = `You are MediSense AI. Generate a concise, printable "Doctor Visit Summary" the patient can take to their doctor.

PATIENT DATA (${reports.length} reports on file):
${reportSummaries}

FORMAT RULES:
- Use clear sections with headings
- Keep it to one page worth of content (roughly 400-600 words)
- Be factual, use the actual values from the data
- Highlight concerning trends and out-of-range values
- List all current medications
- Include specific questions the patient should ask

OUTPUT EXACTLY THIS STRUCTURE (using markdown):

# Doctor Visit Summary
**Generated:** ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
**Reports on File:** ${reports.length} (${new Date(sorted[0].date).toLocaleDateString('en-US', { month: 'short', year: 'numeric' })} – ${new Date(sorted[sorted.length - 1].date).toLocaleDateString('en-US', { month: 'short', year: 'numeric' })})

## Quick Overview
[2-3 sentence overall health picture based on all reports]

## Key Findings & Trends
[Bullet list of the most important biomarker trends, especially any that are out of normal range or changing significantly]

## Active Concerns
[Any risks or conditions flagged across reports]

## Current Medications
[List all medications with dosage and frequency]

## Recommended Discussion Points
[3-5 specific questions for the doctor, referencing actual values]

---
*Generated by MediSense AI. This summary is for discussion purposes only and does not constitute a medical diagnosis.*`;

      const res = await fetch(`${API_BASE}/api/groq/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'llama-3.3-70b-versatile',
          messages: [
            { role: 'system', content: 'You are a medical report summarization assistant. Generate clear, factual, printable summaries. Use markdown formatting.' },
            { role: 'user', content: prompt },
          ],
          temperature: 0.2,
          max_tokens: 1500,
        }),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || `Server returned ${res.status}`);
      }

      const data = await res.json();
      const text = data.choices?.[0]?.message?.content;
      if (!text) throw new Error('Empty response from AI');

      setSummary(text);
    } catch (e: any) {
      console.error('Summary generation error:', e);
      setError(e.message || 'Failed to generate summary');
    } finally {
      setLoading(false);
    }
  };

  const downloadSummary = () => {
    if (!summary) return;
    // Convert markdown to plain text for download (strip markdown symbols)
    const plain = summary
      .replace(/^#{1,6}\s+/gm, '')
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1');

    const blob = new Blob([plain], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `doctor-summary-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const printSummary = () => {
    if (!summary) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    // Convert markdown to basic HTML
    const html = summary
      .replace(/^# (.+)$/gm, '<h1 style="margin:0 0 4px;font-size:22px;">$1</h1>')
      .replace(/^## (.+)$/gm, '<h2 style="margin:16px 0 6px;font-size:16px;color:#374151;">$1</h2>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/^- (.+)$/gm, '<li style="margin:2px 0;">$1</li>')
      .replace(/^---$/gm, '<hr style="margin:16px 0;border-color:#e5e7eb;">')
      .replace(/\n/g, '<br>');

    printWindow.document.write(`<!DOCTYPE html><html><head><title>Doctor Visit Summary</title>
      <style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;color:#111827;font-size:14px;line-height:1.6}h1{color:#1e40af}h2{border-bottom:1px solid #e5e7eb;padding-bottom:4px}li{margin-left:20px}@media print{body{margin:20px}}</style>
      </head><body>${html}</body></html>`);
    printWindow.document.close();
    printWindow.print();
  };

  // Render markdown text in React
  const renderMarkdown = (text: string) => {
    return text.split('\n').map((line, i) => {
      // Headings
      if (line.startsWith('# ')) {
        return <h2 key={i} className="text-xl font-bold text-gray-900 mb-1">{line.slice(2)}</h2>;
      }
      if (line.startsWith('## ')) {
        return <h3 key={i} className="text-sm font-bold text-gray-700 uppercase tracking-wider mt-5 mb-2 border-b border-gray-200 pb-1">{line.slice(3)}</h3>;
      }
      // Horizontal rule
      if (line.trim() === '---') {
        return <hr key={i} className="my-4 border-gray-200" />;
      }
      // Bullet list
      if (line.startsWith('- ')) {
        const content = line.slice(2);
        return (
          <div key={i} className="flex items-start gap-2 ml-2 my-1">
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mt-1.5 shrink-0" />
            <span className="text-sm text-gray-700 leading-relaxed">{renderInline(content)}</span>
          </div>
        );
      }
      // Empty line
      if (line.trim() === '') {
        return <div key={i} className="h-1" />;
      }
      // Normal paragraph
      return <p key={i} className="text-sm text-gray-700 leading-relaxed">{renderInline(line)}</p>;
    });
  };

  const renderInline = (text: string) => {
    // Bold and italic
    const parts = text.split(/(\*\*.*?\*\*|\*.*?\*)/g);
    return parts.map((part, j) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={j} className="font-bold text-gray-900">{part.slice(2, -2)}</strong>;
      }
      if (part.startsWith('*') && part.endsWith('*') && part.length > 2) {
        return <em key={j}>{part.slice(1, -1)}</em>;
      }
      return <span key={j}>{part}</span>;
    });
  };

  if (reports.length === 0) return null;

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white flex items-center justify-center shadow-lg">
          <FileText size={20} />
        </div>
        <div className="flex-1">
          <h3 className="text-lg font-bold text-gray-900">Doctor Visit Summary</h3>
          <p className="text-xs text-gray-400 font-medium">
            AI-generated one-page summary from all your reports
          </p>
        </div>
        {!summary && !loading && (
          <button
            onClick={generateSummary}
            className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl transition-colors shadow-md flex items-center gap-2"
          >
            <FileText size={14} />
            Generate Summary
          </button>
        )}
      </div>

      {error && (
        <div className="bg-red-50 border border-red-100 rounded-xl p-4 flex items-start gap-3">
          <AlertCircle size={18} className="text-red-500 mt-0.5 shrink-0" />
          <div>
            <p className="text-sm font-bold text-red-700">Failed to generate summary</p>
            <p className="text-xs text-red-600 mt-1">{error}</p>
            <button
              onClick={generateSummary}
              className="mt-2 text-xs font-bold text-red-700 underline hover:no-underline"
            >
              Try again
            </button>
          </div>
        </div>
      )}

      {loading && (
        <div className="bg-white rounded-2xl border border-gray-100 p-8 flex flex-col items-center justify-center">
          <Loader2 size={28} className="text-emerald-500 animate-spin mb-3" />
          <p className="text-sm font-medium text-gray-600">Analyzing {reports.length} reports...</p>
          <p className="text-xs text-gray-400 mt-1">Generating your doctor visit summary</p>
        </div>
      )}

      {summary && !loading && (
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
          {/* Action bar */}
          <div className="flex items-center justify-between px-5 py-3 bg-gray-50 border-b border-gray-100">
            <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">Summary Ready</span>
            <div className="flex items-center gap-2">
              <button
                onClick={downloadSummary}
                className="px-3 py-1.5 text-xs font-bold text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 flex items-center gap-1.5 transition-colors"
              >
                <Download size={13} />
                Download
              </button>
              <button
                onClick={printSummary}
                className="px-3 py-1.5 text-xs font-bold text-white bg-emerald-600 rounded-lg hover:bg-emerald-700 flex items-center gap-1.5 transition-colors"
              >
                <FileText size={13} />
                Print
              </button>
              <button
                onClick={generateSummary}
                className="px-3 py-1.5 text-xs font-bold text-gray-500 hover:text-gray-700 transition-colors"
              >
                Regenerate
              </button>
            </div>
          </div>

          {/* Summary content */}
          <div className="px-6 py-5">
            {renderMarkdown(summary)}
          </div>
        </div>
      )}
    </div>
  );
};
